[package]
name = "zkos-client-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
curve25519-dalek = { version = "3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
clear_on_drop = {version = "0.2.4", features = ["no_cc"]}
rand = "0.7"
serde_json = "1.0.58"
#serde_bytes = "0.11.9"
console_error_panic_hook = "0.1.6"
base64 = "*"
bincode = "1.3.3"
hex = "0.4"
sha3 = "0.9.1"
criterion = {version = "0.3", features = ["html_reports"]}
uuid = { version = "0.8.2", features = ["v4", "serde"] }
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"


[dependencies.zkvm]
git = "ssh://github.com/twilight-project/ZkOS.git"
branch = "develop"


[dependencies.transaction]
git = "ssh://github.com/twilight-project/ZkOS.git"
branch = "develop"


[dependencies.transactionapi]
git = "ssh://github.com/twilight-project/ZkOS.git"
branch = "develop"


[dependencies.address]
git = "ssh://github.com/twilight-project/ZkOS.git"
branch = "develop"



[dependencies.zkschnorr]

git = "ssh://github.com/twilight-project/ZkSchnorr.git"

[dependencies.quisquis-rust]

git = "ssh://github.com/twilight-project/quisquis-rust.git"
branch = "develop"